-- MySQL Script generated by MySQL Workbench
-- Wed 23 Nov 2016 01:48:47 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema veranda
-- -----------------------------------------------------
-- Veranda QA platform - CSC 309 project
-- 
DROP SCHEMA IF EXISTS `veranda` ;

-- -----------------------------------------------------
-- Schema veranda
--
-- Veranda QA platform - CSC 309 project
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veranda` DEFAULT CHARACTER SET utf8 ;
USE `veranda` ;

-- -----------------------------------------------------
-- Table `veranda`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Account` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Account` (
  `account_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veranda`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Course` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Course` (
  `course_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(120) NOT NULL,
  `start_date` DATE NULL,
  `finish_date` DATE NULL,
  PRIMARY KEY (`course_id`),
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `createdBy_idx` ON `veranda`.`Course` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`CourseInstructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`CourseInstructor` ;

CREATE TABLE IF NOT EXISTS `veranda`.`CourseInstructor` (
  `course_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`course_id`, `account_id`),
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `veranda`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `accountId_idx` ON `veranda`.`CourseInstructor` (`account_id` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`CourseStudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`CourseStudent` ;

CREATE TABLE IF NOT EXISTS `veranda`.`CourseStudent` (
  `course_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`course_id`, `account_id`),
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `veranda`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `accountId_idx` ON `veranda`.`CourseStudent` (`account_id` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`Thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Thread` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Thread` (
  `thread_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `course_id` INT NOT NULL,
  `is_anon` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`thread_id`, `created_by`, `course_id`),
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `veranda`.`Course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `courseId_idx` ON `veranda`.`Thread` (`course_id` ASC);

CREATE INDEX `createdBy_idx` ON `veranda`.`Thread` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Answer` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Answer` (
  `answer_id` INT NOT NULL,
  `thread_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `content` VARCHAR(300) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `is_anon` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`answer_id`, `thread_id`, `created_by`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `threadId_idx` ON `veranda`.`Answer` (`thread_id` ASC);

CREATE INDEX `createdBy_idx` ON `veranda`.`Answer` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Comment` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Comment` (
  `comment_id` INT NOT NULL,
  `thread_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `is_anon` TINYINT(1) NOT NULL DEFAULT 0,
  `content` VARCHAR(300) NULL,
  PRIMARY KEY (`comment_id`, `thread_id`, `created_by`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `threadId_idx` ON `veranda`.`Comment` (`thread_id` ASC);

CREATE INDEX `createdBy_idx` ON `veranda`.`Comment` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`AnswerVote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`AnswerVote` ;

CREATE TABLE IF NOT EXISTS `veranda`.`AnswerVote` (
  `answer_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`answer_id`, `created_by`),
  CONSTRAINT `fk_answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `veranda`.`Answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `votedBy_idx` ON `veranda`.`AnswerVote` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`ThreadVote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`ThreadVote` ;

CREATE TABLE IF NOT EXISTS `veranda`.`ThreadVote` (
  `thread_id` INT NOT NULL,
  `voted_by` INT NOT NULL,
  PRIMARY KEY (`thread_id`, `voted_by`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voted_by`
    FOREIGN KEY (`voted_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `votedBy_idx` ON `veranda`.`ThreadVote` (`voted_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`Bulletin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Bulletin` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Bulletin` (
  `thread_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `instructor_message` VARCHAR(120) NULL,
  PRIMARY KEY (`thread_id`, `created_by`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `pinnedBy_idx` ON `veranda`.`Bulletin` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`Raised`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`Raised` ;

CREATE TABLE IF NOT EXISTS `veranda`.`Raised` (
  `raised_id` INT NOT NULL,
  `thread_id` INT NOT NULL,
  `created_by` INT NOT NULL,
  `message` VARCHAR(120) NOT NULL,
  `is_closed` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`raised_id`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `raisedBy_idx` ON `veranda`.`Raised` (`created_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`File`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`File` ;

CREATE TABLE IF NOT EXISTS `veranda`.`File` (
  `file_id` INT NOT NULL,
  `filepath` VARCHAR(120) NOT NULL,
  `uploaded_by` INT NOT NULL,
  PRIMARY KEY (`file_id`),
  CONSTRAINT `fk_uploaded_by`
    FOREIGN KEY (`uploaded_by`)
    REFERENCES `veranda`.`Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `filepath_UNIQUE` ON `veranda`.`File` (`filepath` ASC);

CREATE INDEX `fk_uploaded_by_idx` ON `veranda`.`File` (`uploaded_by` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`AnswerFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`AnswerFile` ;

CREATE TABLE IF NOT EXISTS `veranda`.`AnswerFile` (
  `answer_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`answer_id`, `file_id`),
  CONSTRAINT `fk_answer_id`
    FOREIGN KEY (`answer_id`)
    REFERENCES `veranda`.`Answer` (`answer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`file_id`)
    REFERENCES `veranda`.`File` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fileId_idx` ON `veranda`.`AnswerFile` (`file_id` ASC);


-- -----------------------------------------------------
-- Table `veranda`.`ThreadFile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veranda`.`ThreadFile` ;

CREATE TABLE IF NOT EXISTS `veranda`.`ThreadFile` (
  `thread_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  PRIMARY KEY (`thread_id`, `file_id`),
  CONSTRAINT `fk_thread_id`
    FOREIGN KEY (`thread_id`)
    REFERENCES `veranda`.`Thread` (`thread_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_id`
    FOREIGN KEY (`file_id`)
    REFERENCES `veranda`.`File` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fileId_idx` ON `veranda`.`ThreadFile` (`file_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
